# Server
server:
  port: 8484

# Logging
logging:
  config: classpath:logback-prod.xml

# Management
#management:
#  metrics:
#    export:
#      influx:
#        auto-create-db: true
#        batch-size: 10000
#        compressed: true
#        connect-timeout: 1s
#        consistency: one
#        db: skeletonDb
#        enabled: true
#        num-threads: 2
#        password: mysecret
#        read-timeout: 10s
#        step: 1m
#        uri: http://localhost:8086
#        user-name: myusername

# Application Configuration
appConfigs:
  cors:
    enabled: true
    pathPattern: /api/**
    allowedOrigins:
      - http://localhost:8686
      - http://localhost:8787
    allowedMethods:
      - DELETE
      - GET
      - POST
      - PUT
    exposedHeaders:
      - Authorization
    allowCredentials: true
